name: Zedis CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Zedis
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake

      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Show binary
        run: |
          ls -lh build/zedis
          file build/zedis

      - name: Build Docker image
        run: |
          docker build \
            --tag zedis:test \
            .
